'use client';
import { useEffect, useState } from 'react';

type Device = { device_id: string; last_cursor: number; last_seen_at: string; lag: number; stale: boolean; last_error?: string };
type Metrics = { changes: number; mutations: number; audit_entries: number; latest_cursor: number; devices: Device[] };
export default function MonitoringPage() {
  const [data, setData] = useState<Metrics | null>(null); const [error, setError] = useState(false);
  useEffect(() => { const load = () => fetch('/api/monitoring/sync', { cache: 'no-store' }).then(r => r.ok ? r.json() : Promise.reject()).then(setData).catch(() => setError(true)); load(); const id = setInterval(load, 30000); return () => clearInterval(id); }, []);
  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:py-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Exploitation</p><h1 className="mt-1 text-3xl font-black text-slate-900">Santé de la synchronisation</h1>{error && <p className="mt-6 bg-red-50 p-4 text-red-800">Métriques indisponibles.</p>}{!data && !error && <div className="mt-8 h-32 animate-pulse rounded-xl bg-slate-200" />}{data && <><dl className="my-8 grid grid-cols-2 gap-px overflow-hidden rounded-xl bg-slate-200 md:grid-cols-4">{[['Version serveur', data.latest_cursor], ['Changements conservés', data.changes], ['Envois reçus', data.mutations], ['Journal médical', data.audit_entries]].map(([label, value]) => <div key={String(label)} className="bg-white p-5"><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-2 text-2xl font-black text-slate-900">{value}</dd></div>)}</dl><div className="divide-y divide-slate-200 border-y border-slate-200 bg-white md:hidden">{data.devices.map(d => <article key={d.device_id} className="grid grid-cols-2 gap-3 p-4 text-sm"><div><p className="text-xs font-bold uppercase text-slate-500">Appareil</p><p className="mt-1 font-mono">{d.device_id.slice(0, 12)}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">État</p><span className={`mt-1 inline-block rounded-full px-2 py-1 text-xs font-bold ${d.stale || d.last_error ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'}`}>{d.last_error ? 'Erreur' : d.stale ? 'Inactif' : 'À jour'}</span></div><div className="col-span-2"><p className="text-xs font-bold uppercase text-slate-500">Dernière activité</p><p className="mt-1">{new Date(d.last_seen_at).toLocaleString()} · {d.lag} changement(s) à récupérer</p></div></article>)}</div><div className="hidden overflow-x-auto border-y border-slate-200 bg-white md:block"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Appareil</th><th>Dernière activité</th><th>À récupérer</th><th>État</th></tr></thead><tbody className="divide-y divide-slate-100">{data.devices.map(d => <tr key={d.device_id}><td className="p-4 font-mono">{d.device_id.slice(0, 12)}</td><td>{new Date(d.last_seen_at).toLocaleString()}</td><td>{d.lag} changement(s)</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${d.stale || d.last_error ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'}`}>{d.last_error ? 'Erreur' : d.stale ? 'Inactif' : 'À jour'}</span></td></tr>)}</tbody></table></div></>}</div></main>;
}
